channels:
  - conda-forge
  - defaults
dependencies:
  - imbalanced-learn=0.14.1
  - ipykernel=7.2.0
  - ipython=9.10.0
  - keras=3.12.0
  - matplotlib=3.10.8
  - matplotlib-base=3.10.8
  - matplotlib-inline=0.2.1
  - opencv=4.12.0
  - python=3.13.12
  - scikit-learn=1.8.0
  - tensorflow=2.20.0
  - tensorflow-base=2.20.0

